model_params:
  neural_cp:
    input_shape: [30, 1]
    n_changepoints: 3
    latent_dim: 8
  
  causal:
    confidence_level: 0.95
    n_bootstrap: 1000

dashboard:
  port: 8000
  graphql_path: "/graphql"
